apiVersion: apps/v1
kind: Deployment
metadata:
  name: certidz-web
spec:
  replicas: 3
  template:
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: certidz-web
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/name: certidz-web
      containers:
        - name: web
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: "1500m"
              memory: 1Gi
